aws-akey = "[removed]"
aws-skey = "[removed]"
do-token = "[removed]"
cf-email = "[removed]"
cf-token = "[removed]"
rasta-key = "rasta.pub"
attacker-ip = "2.31.13.109/32"
dom1 = "dontgethacked.site"
sub1 = "support"
sub2 = "cpanel"
sub3 = "static"
dom2 = "rekt.site"sub4 = "webdisk"
